export const RecommendFriendData = [
    {
        uid: 12121,
        avtarUrl: 'test1',
        nickname: 'test1',
    },
    {
        uid: 12122,
        avtarUrl: 'test1',
        nickname: 'test1',
    },
    {
        uid: 12123,
        avtarUrl: 'test1',
        nickname: 'test1',
    },
    {
        uid: 12124,
        avtarUrl: 'test1',
        nickname: 'test1',
    },
] as protocol.IBean_Stage_PlayerInfo[];

export const Data2 = {
    ResUid: 179016,
    ResServerTime: 1579004176892,
    Push_Stage_RecvInvite: {
        playerInfo: {
            uid: 179015,
            homeId: 131782,
            status: 3,
            nickname: '游客179015',
            avtarUrl:
                'https://qscdn.gameabc2.com/static/headpic/visitor/19.jpg',
            positionOn: true,
        },
        homeInfo: {
            joinUidMap: {},
            joinPlayerMap: {},
            homeId: 131782,
            ownerUid: 179015,
            status: 1,
            homeType: 2,
            category: 19,
            serverId: 100014,
            homeConfig: {
                serverId: 100014,
                category: 19,
                subCategory: 2,
                locked: false,
                level: 8,
                basePoint: 1,
                minEnterCoin: 0,
                maxEnterCoin: 0,
                openBeginTime: 0,
                openEndTime: 0,
                playerNum: 4,
                hasMan: true,
                hasPin: true,
                hasSou: true,
                hasHonors: false,
                canChow: false,
                canWinByDiscard: false,
                canWinFowlByDiscard: false,
                canWinByRobKong: true,
                robKongWinMultiple: 1,
                sevenPairsMultiple: 0,
                lastTileWinMultiple: 0,
                winAfterKongMultiple: 1,
                redDragonPoint: 1,
                noneGhostMultiple: 0,
                confirmDealer: 2,
                roundDealer: 2,
                followDealer: false,
                higherAndHigher: 0,
                drawnWithKong: false,
                openGhostType: 3,
                fourGhostWin: false,
                robKongContract: false,
                kongBombContract: false,
                twelveGroundContract: false,
                buyHorseType: 0,
                horseNum: 0,
                cost: 0,
                roundNum: 16,
                systemCountdownTime: 0,
                trusteeTimeoutCount: 0,
                balanceCountdown: 20,
                aiSwitch: false,
                openChickenRule: 0,
                blackBoneChicken: true,
                wholeHouse: true,
                beanWrap: false,
                chickenWrap: false,
                robKongBean: true,
                robKongChicken: true,
                tumoAddOne: false,
                voiceSwitch: true,
                positionSwitch: false,
                ronWin: false,
                chickenCantRonwin: false,
                smallWin: false,
                twoRoomCard: false,
                ownChicken: true,
                highLowChicken: true,
                openCardChicken: true,
                numbericHorse: false,
                playerNumRaw: 4,
                maxWin: 0,
                changeCard: false,
                callForwarding: false,
                tumoMutiple: 1,
                pointBar: 0,
                menQing: 0,
                daiYaojiu: 0,
                duanYaojiu: 0,
                jiangDui: 0,
                skyLand: 0,
                investTime: 0,
                flowerPigFan: 0,
                chuifengji: false,
                wawaji: false,
                huangleji: 0,
                chongfengji: 2,
                chongfengwuguji: 3,
                zerenji: 1,
                name: '',
                ruleid: 0,
                tianting: 10,
                qianhouji: false,
                xingqiji: true,
                yinji: false,
                shortcard: false,
                xiaohubimen: true,
                tiantingruanbao: 0,
                tiantingyingbao: 0,
            },
        },
    },
};
